apiVersion: v1
kind: Service
metadata:
  name: {{ include "modelservice.fullname" . }}
  labels:
    {{- include "modelservice.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "modelservice.selectorLabels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ports:
    - name: modelserver
      port: 8000
      targetPort: modelserver
      protocol: TCP
    {{- range .Values.extraPorts }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
